### ISSUE TITLE
Questions about hyperparameters

### ISSUE THREAD

**Issue by superarthurlx** [chaoshangcs/GTS#11]
I cannot get the result listed in the paper after running the code. I tried grid search but it takes quite a long time. So can you provide the final hyperparameters about the model?  Thank you.

**Comment by chaoshangcs** [comment]
Hi, thanks for your message. First, we have updated the results in table 4, 5 and 6 with corresponding explanation in the paper. I recommend to check the new results. 
Second, we do upgrade our implementation after receiving many valuable feedbacks. The hyperparameters might be different. Tuning the lr and lr steps will be helpful. 
Third, there are two RMSE calculations. The first one is to calculate the rmse of each batch and do average. In the current implementation, we calculate the mse, do the average and take the square root of it. Both of two options are reasonable. The first calculation will have a higher rmse value.

**Comment by superarthurlx** [comment]
Thanks for your reply, it's a great work.
