### ISSUE TITLE
Problem of RMSE calculation of each horizon

### ISSUE THREAD

**Issue by linar722** [chaoshangcs/GTS#7]
Hi, I notice that when evaluating the model, you calculate the RMSE of each batch first (line 179, 182, 185) and then average it (line 240). This will lower the true RMSE loss.

I think RMSE should be computed either like DCRNN (concatenate all batches then evaluate for each horizon) or by calculating the MSE of each batch then taking the square root of its mean.

**Comment by chaoshangcs** [comment]
Hi, thanks a lot for your remind. We have modified the implementation based on your suggestion. If you have any other questions, please let me know.
